server:
port: 8080
spring:
datasource:
  url: jdbc:h2:file:~//salaodebeleza;DB_CLOSE_ON_EXIT=FALSE
  username: root
  password: root
  mvc:
  pathmatch:
    matching-strategy: ant_path_matcher
jpa:
  hibernate.ddl-auto: update
  spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

