server:
port: 8083
spring:
datasource:
  url: jdbc:h2:mem:greeter-quickstart;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
  username: root
  password: root
  mvc:
  pathmatch:
    matching-strategy: ant_path_matcher
jpa:
  hibernate.ddl-auto: update
  spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
