server:
port: 8083
spring:
datasource:
  url: jdbc:mysql://localhost:3306/dbMySql1
  username: root
  password: root
  mvc:
  pathmatch:
    matching-strategy: ant_path_matcher
jpa:
  hibernate.ddl-auto: update
  spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
